### ISSUE TITLE
关于实现有点问题探讨

### ISSUE THREAD

**Issue by lifefloating** [gumengkai/db_monitor#6]
你好，大概看了下代码， 思路好像还是走sql查一些基本信息啊 ：show global variables like xxx 这种
开始我因为是项目还有个后台项目或者是走snmp那样的，网表里写数据的。
方便问下这个项目一些指标数据是还有后台项目 吗 如果有的话建议放那个，感觉更有价值点

**Comment by gumengkai** [comment]
现在的实现就是这样了，基本是通过ssh或者sql

**Comment by lifefloating** [comment]
> 现在的实现就是这样了，基本是通过ssh或者sql

了解了，我开始以为你是还有个后台项目的，后面看到是通过sql的。 可以的

**Comment by gumengkai** [comment]
.
